os: linux
language: cpp
dist: bionic
compiler: gcc

branches:
  only:
    - task2-dev
  except:
    - main

install:
  - sudo apt-get update
  - sudo apt-get install cmake make valgrind cppcheck gcovr
  - pip install cpplint

before_script:
  - sh scripts/build.sh

script:
  - sh scripts/memleak_test.sh
  - sh scripts/linters_test.sh
  - cd build
  - ctest --verbose
  - make hw_1_14_coverage
  - export CODECOV_TOKEN="9757ba56-aa1b-4e4b-b06f-838261b81dfc"
  - bash <(curl -s https://codecov.io/bash) -Z
